postgresql:
  url: postgres://postgres@localhost/cc-scanner

bitcoind: # config for https://github.com/bitpay/bitcoind-rpc
  protocol: http
  user: bitcoinrpc
  pass: password_to_your_bitcoind
  host: localhost
  port: 18332
