postgresql:
  url: postgres://vagrant:somepassword@localhost/cc_scanner

bitcoind: # config for https://github.com/bitpay/bitcoind-rpc
  protocol: http
  user: bitcoinrpc
  pass: password_to_your_bitcoind
  host: localhost
  port: 18332

service:
  port: 4445
